### ISSUE TITLE
Parsing error when using project-away *1

### ISSUE THREAD

**Issue by f-bader** [FalconForceTeam/KQLAnalyzer#2]
When I use the `project-away` operator and a Wildcard `*` the parsing breaks

```json
{
  "query": "SigninLogs | limit 10 | project UserId, UserPrincipalName | join kind=inner (IdentityInfo | where TimeGenerated > ago(14d) | summarize arg_max(TimeGenerated,*) by AccountObjectId ) on $left.UserId == $right.AccountObjectId | project-away *1",
  "environment": "sentinel",
  "local_data": {}
}
```

Parsing error

```json
{
      "Code": "KS142",
      "Category": "General",
      "Severity": "Error",
      "Description": "The name \u0027*1\u0027 does not refer to any known column, table, variable or function.",
      "Message": "The name \u0027*1\u0027 does not refer to any known column, table, variable or function.",
      "HasLocation": true,
      "LocationKind": 0,
      "Start": 238,
      "Length": 2,
      "End": 240
    }
```

Cheers, Fabian

**Comment by gijsh** [comment]
Hi Fabian, thanks for your report and apologies for the late reply.

The KQL analyzer uses an upstream project to parse the KQL https://github.com/microsoft/Kusto-Query-Language/tree/master/src/Kusto.Language.

This analyzer is a bit more strict than the analyzer that Sentinel uses. In this case according to the schemas there is no column which ends in 1 so `| project-away *1` does not match any column and therefore returns an error.

I believe it's this code in the upstream that causes this:
https://github.com/microsoft/Kusto-Query-Language/blob/969ae8195000f270d72e43cfb4eb0d5e6092400c/src/Kusto.Language/Binder/Binder_NodeBinder.cs#L649
